### ISSUE TITLE
@grammyjs/storage-file not working when deployed

### ISSUE THREAD

**Issue by tanjunior** [waptik/grammy-on-deta-template#6]
I really like this addon but it seems like it's not working when deployed.

https://www.npmjs.com/package/@grammyjs/storage-file

**Comment by waptik** [comment]
> I really like this addon but it seems like it's not working when deployed.
> 
> [npmjs.com/package/@grammyjs/storage-file](https://www.npmjs.com/package/@grammyjs/storage-file)

I've never used that plugin before and i don't have time to test it at the moment. Sorry, can't help
